load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "starlarklibrary",
    srcs = ["language.go"],
    importpath = "github.com/stackb/rules_proto/language/starlarklibrary",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//config:go_default_library",
        "@bazel_gazelle//label:go_default_library",
        "@bazel_gazelle//language:go_default_library",
        "@bazel_gazelle//pathtools:go_default_library",
        "@bazel_gazelle//repo:go_default_library",
        "@bazel_gazelle//resolve:go_default_library",
        "@bazel_gazelle//rule:go_default_library",
        "@com_github_bazelbuild_buildtools//build:go_default_library",
    ],
)

go_test(
    name = "starlarklibrary_test",
    srcs = [
        "bazelignore_test.go",
        "dict_test.go",
        "lifecycle_test.go",
        "starlark_library_test.go",
    ],
    embed = [":starlarklibrary"],
    deps = [
        "@bazel_gazelle//config:go_default_library",
        "@com_github_bazelbuild_buildtools//build:go_default_library",
    ],
)
