/* Copyright 2020 The Bazel Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package symbol generates a `starlark_library` target for every `.bzl` file in
// each package.  At the root of the module, a single starlark_library is
// populated with deps that include all other starlark_libraries.
//
// The original code for this gazelle extension started from
// https://github.com/bazelbuild/bazel-skylib/blob/main/gazelle/bzl/gazelle.go.
package starlarklibrary

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/bazelbuild/buildtools/build"
)

const (
	languageName          = "starlarklibrary"
	repoNameDirectiveName = languageName + "_repo_name"
	rootDirectiveName     = languageName + "_root"
	excludeDirectiveName  = languageName + "_exclude"
	logFileDirectiveName  = languageName + "_log_file"
	starlarkLibraryKind   = "starlark_library"
	starlarkLibraryName   = "bzl_srcs"
	fileType              = ".bzl"
	visibilityPublic      = "//visibility:public"
)

var (
	ignoreSuffix = suffixes{
		"_tests.bzl",
		"_test.bzl",
	}
	starlarkLibraryKindInfo = map[string]rule.KindInfo{
		starlarkLibraryKind: {
			NonEmptyAttrs: map[string]bool{"srcs": true},
			ResolveAttrs:  map[string]bool{"deps": true},
		},
	}
	starlarkLibraryLoadInfo = rule.LoadInfo{
		Name:    "@build_stack_rules_proto//rules:starlark_library.bzl",
		Symbols: []string{starlarkLibraryKind},
	}
)

type starlarkLibraryLang struct {
	roots        []string
	repoName     string
	excludeDirs  []string
	bazelVersion string
	bazelIgnore  []string
	logFile      string
	logWriter    *os.File
	logger       *log.Logger
}

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &starlarkLibraryLang{}
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (*starlarkLibraryLang) Name() string {
	return languageName
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (ext *starlarkLibraryLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&ext.logFile, logFileDirectiveName, "", "path to log file for starlark_library extension")
}

func (ext *starlarkLibraryLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	if ext.logFile != "" {
		ext.createLogger(ext.logFile)
		ext.logf("CheckFlags: log file initialized from flag: %s", ext.logFile)
	}
	if ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}

	// REPO.bazel causes visibility issues if the root BUILD file has been
	// deleted but still referencing non-existent rules.  This should be
	// moved to the part where gazelle cleans up build files.
	repoBazelFilename := filepath.Join(c.RepoRoot, "REPO.bazel")
	deleteFile(repoBazelFilename, ext.logf)

	bazelVersionFilename := filepath.Join(c.RepoRoot, ".bazelversion")
	if lines, err := readFileLines(bazelVersionFilename, ext.logf); err == nil {
		ext.bazelVersion = strings.Join(lines, ":")
		deleteFile(bazelVersionFilename, ext.logf)
	}

	bazelIgnoreFilename := filepath.Join(c.RepoRoot, ".bazelignore")
	if lines, err := readFileLines(bazelIgnoreFilename, ext.logf); err == nil {
		ext.bazelIgnore = lines
		deleteFile(bazelIgnoreFilename, ext.logf)
	}

	return nil
}

func (*starlarkLibraryLang) KnownDirectives() []string {
	return []string{
		rootDirectiveName,
		excludeDirectiveName,
		logFileDirectiveName,
	}
}

func (ext *starlarkLibraryLang) Configure(c *config.Config, rel string, f *rule.File) {
	if f != nil {
		ext.logf("Configure: processing %d directives in %s", len(f.Directives), rel)
		for _, d := range f.Directives {
			switch d.Key {
			case rootDirectiveName:
				ext.roots = append(ext.roots, d.Value)
			case repoNameDirectiveName:
				ext.repoName = d.Value
			case excludeDirectiveName:
				ext.excludeDirs = append(ext.excludeDirs, d.Value)
			case logFileDirectiveName:
				ext.createLogger(d.Value)
			}
		}
	}
}

func (ext *starlarkLibraryLang) createLogger(logFile string) {
	if logFile != "" {
		f, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0666)
		if err == nil {
			ext.logWriter = f
			ext.logger = log.New(f, "", log.LstdFlags)
		} else {
			log.Fatalf("attempting to open log file: %v", err)
		}
	}
	if false && ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}

	ext.logf("Log initialized")
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*starlarkLibraryLang) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{}
	maps.Copy(kinds, starlarkLibraryKindInfo)
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (*starlarkLibraryLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		starlarkLibraryLoadInfo,
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*starlarkLibraryLang) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (ext *starlarkLibraryLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	srcs := r.AttrStrings("srcs")
	imports := make([]resolve.ImportSpec, 0, len(srcs)+1)

	for _, src := range srcs {
		spec := resolve.ImportSpec{
			Lang: languageName,
			Imp:  fmt.Sprintf("//%s:%s", f.Pkg, src),
		}

		imports = append(imports, spec)
	}

	// add an import such the one can find *all* the stark_library rules.
	imports = append(imports, resolve.ImportSpec{
		Lang: languageName,
		Imp:  starlarkLibraryKind,
	})

	return imports
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*starlarkLibraryLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (ext *starlarkLibraryLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, importsRaw interface{}, from label.Label) {
	switch r.Kind() {
	case starlarkLibraryKind:
		ext.starlarkLibraryResolve(c, ix, rc, r, importsRaw, from)
	}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (ext *starlarkLibraryLang) GenerateRules(args language.GenerateArgs) (result language.GenerateResult) {
	// extension is effectively disabled without specifying at least one root
	if len(ext.roots) == 0 {
		return
	}
	// skip excluded dirs
	for _, dir := range ext.excludeDirs {
		if strings.HasPrefix(args.Rel, dir) {
			return
		}
	}

	ext.logf("GenerateRules %v: visiting %s", ext.roots, args.Rel)

	// collect all .bzl srcs
	var srcs []string
	for _, f := range append(args.RegularFiles, args.GenFiles...) {
		if isBzlSourceFile(f) {
			srcs = append(srcs, f)
		}
	}

	if len(srcs) == 0 {
		return
	}

	r, imports := ext.starlarkLibraryRule(args, srcs)
	result.Gen = append(result.Gen, r)
	result.Imports = append(result.Imports, imports)

	// if slices.Contains(ext.roots, args.Rel) {
	// 	r, imports := ext.starlarkLibraryRule(args, srcs)
	// 	result.Gen = append(result.Gen, r)
	// 	result.Imports = append(result.Imports, imports)
	// }

	return
}

func (ext *starlarkLibraryLang) starlarkLibraryRule(args language.GenerateArgs, srcs []string) (*rule.Rule, []any) {
	loadsByRelPath := make(map[string][]string)
	for _, src := range srcs {
		relPath := filepath.Join(args.Rel, src)
		fullPath := filepath.Join(args.Config.RepoRoot, relPath)
		_, stmts, err := getBzlFileLoadsStmts(fullPath, args.Rel, ext.logf)

		if err != nil {
			ext.logf("%s: contains syntax errors: %v", fullPath, err)
			// don't return early since it is reasonable to create a target even
			// without deps.
		}
		loads := make([]string, 0, len(stmts))
		for _, stmt := range stmts {
			loads = append(loads, stmt.Module.Value)
		}
		loadsByRelPath[relPath] = loads
	}

	r := rule.NewRule(starlarkLibraryKind, starlarkLibraryName)
	r.SetAttr("srcs", slices.Sorted(maps.Keys(loadsByRelPath)))
	r.SetAttr("loads", stringListDict(loadsByRelPath))
	if ext.repoName != "" {
		r.SetAttr("repo_name", ext.repoName)
	}
	if ext.bazelVersion != "" {
		r.SetAttr("bazelversion", ext.bazelVersion)
	}
	if len(ext.bazelIgnore) > 0 {
		r.SetAttr("bazelignore", ext.bazelIgnore)
	}
	r.SetAttr("visibility", []string{visibilityPublic})

	return r, []any{loadsByRelPath}
}

func (ext *starlarkLibraryLang) starlarkLibraryResolve(c *config.Config, ix *resolve.RuleIndex, _ *repo.RemoteCache, r *rule.Rule, _ interface{}, from label.Label) {
	// only perform resolve if this is one of the roots
	var root *string
	for _, dir := range ext.roots {
		if dir == from.Pkg {
			root = &dir
			break
		}
	}
	if root == nil {
		ext.logf("skipping deps resolution for %v (not a root: %v)", from, ext.roots)
		return
	}

	var deps []string

	// fetch all rules, then filter by the ones below our root
	matches := ix.FindRulesByImportWithConfig(c, resolve.ImportSpec{
		Lang: languageName,
		Imp:  starlarkLibraryKind,
	}, languageName)
	for _, m := range matches {
		depLabel := m.Label.Rel(from.Repo, from.Pkg)
		if strings.HasPrefix(depLabel.Pkg, *root) {
			deps = append(deps, depLabel.String())
		}
	}

	if len(deps) > 0 {
		sort.Strings(deps)
		r.SetAttr("deps", deps)
	}
}

// Before implements part of the language.LifecycleManager interface.
func (ext *starlarkLibraryLang) Before(context.Context) {
	ext.logf("Lifecycle: Before() called")
	ext.logf("roots: %v", ext.roots)
}

// DoneGeneratingRules implements part of the language.FinishableLanguage interface.
func (ext *starlarkLibraryLang) DoneGeneratingRules() {
	ext.logf("Lifecycle: DoneGeneratingRules() called")
}

// AfterResolvingDeps implements part of the language.LifecycleManager interface.
// This is where we flush and close the log file.
func (ext *starlarkLibraryLang) AfterResolvingDeps(context.Context) {
	ext.logf("Lifecycle: AfterResolvingDeps() called - flushing and closing log file")
	if ext.logWriter != nil {
		// Sync flushes any buffered data to disk
		_ = ext.logWriter.Sync()
		// Close the file
		_ = ext.logWriter.Close()
		ext.logWriter = nil
	}
}

// logf logs a message using the extension's logger if configured
func (ext *starlarkLibraryLang) logf(format string, args ...any) {
	if ext.logger != nil {
		ext.logger.Printf(format, args...)
	}
}

type suffixes []string

func (s suffixes) Matches(test string) bool {
	for _, v := range s {
		if strings.HasSuffix(test, v) {
			return true
		}
	}
	return false
}

// LogFunc is a function type for logging messages
type LogFunc func(format string, args ...any)

// deleteFile removes a file and logs any errors
func deleteFile(filename string, logf LogFunc) {
	if err := os.Remove(filename); err != nil {
		logf("ERROR: failed to remove %s: %v", filename, err)
	}
}

// readFileLines reads a file and returns a slice of trimmed non-empty lines,
// excluding comments (lines starting with #).
func readFileLines(filePath string, logf LogFunc) ([]string, error) {
	logf("Reading lines from file: %s", filePath)

	// Open the file
	file, err := os.Open(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			logf("  File does not exist")
			return nil, err
		}
		return nil, fmt.Errorf("failed to open file: %w", err)
	}
	defer file.Close()

	// Scan lines using bufio.Scanner
	scanner := bufio.NewScanner(file)
	var lines []string

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Skip empty lines
		if trimmed == "" {
			continue
		}

		// Skip comments
		if strings.HasPrefix(trimmed, "#") {
			continue
		}

		lines = append(lines, trimmed)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to scan file: %w", err)
	}

	logf("  Read %d non-empty lines", len(lines))
	return lines, nil
}

func isBzlSourceFile(f string) bool {
	return strings.HasSuffix(f, fileType) && !ignoreSuffix.Matches(f)
}

func getBzlFileLoadsStmts(path, rel string, logf LogFunc) (*build.File, []*build.LoadStmt, error) {
	f, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("os.ReadFile(%q) error: %v", path, err)
	}
	ast, err := build.ParseBzl(path, f)
	if err != nil {
		return nil, nil, fmt.Errorf("build.Parse(%q) error: %v", f, err)
	}

	var loads []*build.LoadStmt
	build.WalkOnce(ast, func(expr *build.Expr) {
		n := *expr
		if l, ok := n.(*build.LoadStmt); ok {
			if lbl, err := label.Parse(l.Module.Value); err == nil {
				l.Module.Value = lbl.Abs("", rel).String()
			} else {
				logf("rel=%q: load parse error: %s %v", rel, l.Module.Value, err)
			}
			loads = append(loads, l)
		}
	})

	return ast, loads, nil
}

// stringListDict creates a Dict expression with string keys and List values
// containing StringExpr elements. Used for representing load statements by file.
func stringListDict(data map[string][]string) *build.DictExpr {
	if len(data) == 0 {
		return &build.DictExpr{}
	}

	// Sort keys for deterministic output
	keys := slices.Sorted(maps.Keys(data))

	var keyValues []*build.KeyValueExpr
	for _, key := range keys {
		values := data[key]

		// Create list of string expressions for the values
		var listExprs []build.Expr
		for _, value := range values {
			listExprs = append(listExprs, &build.StringExpr{Value: value})
		}

		keyValues = append(keyValues, &build.KeyValueExpr{
			Key:   &build.StringExpr{Value: key},
			Value: &build.ListExpr{List: listExprs},
		})
	}

	return &build.DictExpr{
		List: keyValues,
	}
}
