load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "starlarkrepository",
    srcs = ["language.go"],
    importpath = "github.com/stackb/rules_proto/v4/language/starlarkrepository",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//language",
        "@bazel_gazelle//repo",
        "@bazel_gazelle//resolve",
        "@bazel_gazelle//rule",
        "@com_github_bazelbuild_buildtools//build",
    ],
)

go_test(
    name = "starlarkrepository_test",
    srcs = ["language_test.go"],
    embed = [":starlarkrepository"],
    deps = ["@com_github_bazelbuild_buildtools//build"],
)
