/* Copyright 2020 The Bazel Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package symbol generates a `starlark_library` target for every `.bzl` file in
// each package.  At the root of the module, a single starlark_library is
// populated with deps that include all other starlark_libraries.
//
// The original code for this gazelle extension started from
// https://github.com/bazelbuild/bazel-skylib/blob/main/gazelle/bzl/gazelle.go.
package starlarkrepository

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/bazelbuild/buildtools/build"
)

const (
	languageName               = "starlarkrepository"
	repoNameDirectiveName      = languageName + "_repo_name"
	rootDirectiveName          = languageName + "_root"
	excludeDirectiveName       = languageName + "_exclude"
	logFileDirectiveName       = languageName + "_log_file"
	starlarkModuleKind         = "starlark_module"
	starlarkModuleLibraryKind  = "starlark_module_library"
	starlarkModuleLibraryName  = "modules"
	starlarkPackageKind        = "starlark_package"
	starlarkPackageLibraryKind = "starlark_package_library"
	starlarkPackageLibraryName = "starlark_packages"
	bzlFileType                = ".bzl"
	packageFileType            = ".package"
	visibilityPublic           = "//visibility:public"
)

var (
	ignoreSuffix = suffixes{
		"_tests.bzl",
		"_test.bzl",
	}
	starlarkModuleLibraryKindInfo = map[string]rule.KindInfo{
		starlarkModuleLibraryKind: {
			NonEmptyAttrs: map[string]bool{"modules": true},
			ResolveAttrs:  map[string]bool{"modules": true},
		},
	}
	starlarkModuleKindInfo = map[string]rule.KindInfo{
		starlarkModuleKind: {
			NonEmptyAttrs: map[string]bool{"src": true},
		},
	}
	starlarkPackageLibraryKindInfo = map[string]rule.KindInfo{
		starlarkPackageLibraryKind: {
			NonEmptyAttrs: map[string]bool{"packages": true},
			ResolveAttrs:  map[string]bool{"packages": true},
		},
	}
	starlarkPackageKindInfo = map[string]rule.KindInfo{
		starlarkPackageKind: {
			NonEmptyAttrs: map[string]bool{"src": true},
		},
	}
	starlarkModuleLibraryLoadInfo = rule.LoadInfo{
		Name:    "@build_stack_rules_proto//rules:starlark_module_library.bzl",
		Symbols: []string{starlarkModuleLibraryKind},
	}
	starlarkModuleLoadInfo = rule.LoadInfo{
		Name:    "@build_stack_rules_proto//rules:starlark_module.bzl",
		Symbols: []string{starlarkModuleKind},
	}
	starlarkPackageLibraryLoadInfo = rule.LoadInfo{
		Name:    "@build_stack_rules_proto//rules:starlark_package_library.bzl",
		Symbols: []string{starlarkPackageLibraryKind},
	}
	starlarkPackageLoadInfo = rule.LoadInfo{
		Name:    "@build_stack_rules_proto//rules:starlark_package.bzl",
		Symbols: []string{starlarkPackageKind},
	}
)

type starlarkRepositoryLang struct {
	roots        []string
	repoName     string
	excludeDirs  []string
	bazelVersion string
	bazelIgnore  []string
	logFile      string
	logWriter    *os.File
	logger       *log.Logger
}

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &starlarkRepositoryLang{
		excludeDirs: []string{
			"docs",
			"javatests",
			"testdata",
			"tests",
		},
	}
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (*starlarkRepositoryLang) Name() string {
	return languageName
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (ext *starlarkRepositoryLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&ext.logFile, logFileDirectiveName, "", "path to log file for this extension")
}

func (ext *starlarkRepositoryLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	if ext.logFile != "" {
		ext.createLogger(ext.logFile)
		ext.logf("CheckFlags: log file initialized from flag: %s", ext.logFile)
	}
	if ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}

	// REPO.bazel causes visibility issues if the root BUILD file has been
	// deleted but still referencing non-existent rules.  This should be moved
	// to the part where gazelle cleans up build files.
	repoBazelFilename := filepath.Join(c.RepoRoot, "REPO.bazel")
	deleteFile(repoBazelFilename, ext.logf)

	bazelVersionFilename := filepath.Join(c.RepoRoot, ".bazelversion")
	if lines, err := readFileLines(bazelVersionFilename, ext.logf); err == nil {
		ext.bazelVersion = strings.Join(lines, ":")
		deleteFile(bazelVersionFilename, ext.logf)
	}

	bazelIgnoreFilename := filepath.Join(c.RepoRoot, ".bazelignore")
	if lines, err := readFileLines(bazelIgnoreFilename, ext.logf); err == nil {
		ext.bazelIgnore = lines
		deleteFile(bazelIgnoreFilename, ext.logf)
	}

	return nil
}

func (*starlarkRepositoryLang) KnownDirectives() []string {
	return []string{
		rootDirectiveName,
		excludeDirectiveName,
		logFileDirectiveName,
	}
}

func (ext *starlarkRepositoryLang) Configure(c *config.Config, rel string, f *rule.File) {
	if f != nil {
		ext.logf("Configure: processing %d directives in %s", len(f.Directives), rel)
		for _, d := range f.Directives {
			switch d.Key {
			case rootDirectiveName:
				ext.roots = append(ext.roots, d.Value)
			case repoNameDirectiveName:
				ext.repoName = d.Value
			case excludeDirectiveName:
				ext.excludeDirs = append(ext.excludeDirs, d.Value)
			case logFileDirectiveName:
				ext.createLogger(d.Value)
			}
		}
	}
}

func (ext *starlarkRepositoryLang) createLogger(logFile string) {
	if logFile != "" {
		f, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0666)
		if err == nil {
			ext.logWriter = f
			ext.logger = log.New(f, "", log.LstdFlags)
		} else {
			log.Fatalf("attempting to open log file: %v", err)
		}
	}
	if false && ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}

	ext.logf("Log initialized")
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*starlarkRepositoryLang) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{}
	maps.Copy(kinds, starlarkModuleLibraryKindInfo)
	maps.Copy(kinds, starlarkModuleKindInfo)
	maps.Copy(kinds, starlarkPackageLibraryKindInfo)
	maps.Copy(kinds, starlarkPackageKindInfo)
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (*starlarkRepositoryLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		starlarkModuleLibraryLoadInfo,
		starlarkModuleLoadInfo,
		starlarkPackageLibraryLoadInfo,
		starlarkPackageLoadInfo,
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*starlarkRepositoryLang) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (ext *starlarkRepositoryLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	switch r.Kind() {
	case starlarkModuleKind:
		return ext.starlarkModuleImports(c, r, f)
	case starlarkPackageKind:
		return ext.starlarkPackageImports(c, r, f)
	default:
		return nil
	}
}

func (ext *starlarkRepositoryLang) starlarkModuleImports(_ *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	// return one for file level dep resolution, one for the rule kind itself
	return []resolve.ImportSpec{
		{Lang: languageName, Imp: fmt.Sprintf("//%s:%s", f.Pkg, r.AttrString("src"))},
		{Lang: languageName, Imp: starlarkModuleKind},
	}
}

func (ext *starlarkRepositoryLang) starlarkPackageImports(_ *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return []resolve.ImportSpec{
		{Lang: languageName, Imp: fmt.Sprintf("//%s:%s", f.Pkg, r.AttrString("src"))},
		{Lang: languageName, Imp: starlarkPackageKind},
	}
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*starlarkRepositoryLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (ext *starlarkRepositoryLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, importsRaw interface{}, from label.Label) {
	switch r.Kind() {
	case starlarkModuleLibraryKind:
		ext.starlarkModuleLibraryResolve(c, ix, rc, r, importsRaw, from)
	case starlarkPackageLibraryKind:
		ext.starlarkPackageLibraryResolve(c, ix, rc, r, importsRaw, from)
	}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (ext *starlarkRepositoryLang) GenerateRules(args language.GenerateArgs) (result language.GenerateResult) {
	// extension is effectively disabled without specifying at least one root
	if len(ext.roots) == 0 {
		return
	}
	// skip excluded dirs
	for _, dir := range ext.excludeDirs {
		if strings.HasPrefix(args.Rel, dir) {
			return
		}
	}

	ext.logf("GenerateRules %v: visiting %s: %v", ext.roots, args.Rel, args.RegularFiles)
	mustListFiles(ext.logf, filepath.Join(args.Config.WorkDir, args.Rel))
	for _, f := range args.RegularFiles {
		if !isBzlSourceFile(f) {
			continue
		}
		relPath := filepath.Join(args.Rel, f)
		fullPath := filepath.Join(args.Config.WorkDir, relPath)

		_, loadStmts, err := getBzlFileLoadsStmts(fullPath, args.Rel, ext.logf)
		if err != nil {
			ext.logf("%s: contains syntax errors: %v", fullPath, err)
			continue
		}

		r, imports := ext.starlarkModuleRule(args, f, loadStmts)
		result.Gen = append(result.Gen, r)
		result.Imports = append(result.Imports, imports)
		log.Printf("generated %s %s/%s", r.Kind(), args.Rel, r.Name())
	}

	for _, f := range args.RegularFiles {
		if !isBuildPackageFile(f) {
			continue
		}
		r, imports := ext.starlarkPackageRule(args, f)
		result.Gen = append(result.Gen, r)
		result.Imports = append(result.Imports, imports)
		log.Printf("generated %s %s/%s", r.Kind(), args.Rel, r.Name())
	}

	if _, ok := getMatchingRoot(args.Rel, ext.roots); ok {
		r, imports := ext.starlarkModuleLibraryRule(args)
		result.Gen = append(result.Gen, r)
		result.Imports = append(result.Imports, imports)

		r, imports = ext.starlarkPackageLibraryRule(args)
		result.Gen = append(result.Gen, r)
		result.Imports = append(result.Imports, imports)
	}

	return
}

// mustListFiles - convenience debugging function to log the files under a given
// dir, excluding proto files and the extra binaries here.
func mustListFiles(logf LogFunc, dir string) []string {
	files := make([]string, 0)

	if err := filepath.Walk(dir, func(relname string, info os.FileInfo, err error) error {
		if err != nil {
			log.Fatal(err)
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(relname) == ".proto" {
			return nil
		}
		files = append(files, relname)
		logf("file: %s", relname)
		return nil
	}); err != nil {
		logf("walk error: %v", err)
	}

	return files
}
func (ext *starlarkRepositoryLang) starlarkModuleRule(args language.GenerateArgs, src string, loadStmts []*build.LoadStmt) (*rule.Rule, []any) {

	name := strings.TrimSuffix(src, bzlFileType)
	ext.logf("generating %s rule for %s //%s:%s", starlarkModuleKind, src, args.Rel, name)

	loads := make([]string, 0, len(loadStmts))
	for _, stmt := range loadStmts {
		loads = append(loads, stmt.Module.Value)
	}
	sort.Strings(loads)

	r := rule.NewRule(starlarkModuleKind, name)
	r.SetAttr("src", src)
	r.SetAttr("loads", loads)
	r.SetAttr("visibility", []string{visibilityPublic})

	return r, []any{}
}

func (ext *starlarkRepositoryLang) starlarkModuleLibraryRule(_ language.GenerateArgs) (*rule.Rule, []any) {
	r := rule.NewRule(starlarkModuleLibraryKind, starlarkModuleLibraryName)
	if ext.repoName != "" {
		r.SetAttr("repo_name", ext.repoName)
	}
	if ext.bazelVersion != "" {
		r.SetAttr("bazelversion", ext.bazelVersion)
	}
	if len(ext.bazelIgnore) > 0 {
		r.SetAttr("bazelignore", ext.bazelIgnore)
	}
	r.SetAttr("visibility", []string{visibilityPublic})
	return r, []any{}
}

func (ext *starlarkRepositoryLang) starlarkPackageRule(args language.GenerateArgs, src string) (*rule.Rule, []any) {
	// Sanitize the filename into a target name: "BUILD.package" -> "BUILD_package",
	// "BUILD.bazel.package" -> "BUILD_bazel_package". This avoids clashing with
	// `pkg.bzl`-derived `starlark_module(name = "pkg")` targets that exist in many
	// Starlark codebases.
	name := strings.ReplaceAll(src, ".", "_")
	ext.logf("generating %s rule for %s //%s:%s", starlarkPackageKind, src, args.Rel, name)

	r := rule.NewRule(starlarkPackageKind, name)
	r.SetAttr("src", src)
	r.SetAttr("visibility", []string{visibilityPublic})

	return r, []any{}
}

func (ext *starlarkRepositoryLang) starlarkPackageLibraryRule(_ language.GenerateArgs) (*rule.Rule, []any) {
	r := rule.NewRule(starlarkPackageLibraryKind, starlarkPackageLibraryName)
	if ext.bazelVersion != "" {
		r.SetAttr("bazelversion", ext.bazelVersion)
	}
	if len(ext.bazelIgnore) > 0 {
		r.SetAttr("bazelignore", ext.bazelIgnore)
	}
	r.SetAttr("visibility", []string{visibilityPublic})
	return r, []any{}
}

func (ext *starlarkRepositoryLang) starlarkPackageLibraryResolve(c *config.Config, ix *resolve.RuleIndex, _ *repo.RemoteCache, r *rule.Rule, _ interface{}, from label.Label) {
	root, isRoot := getMatchingRoot(from.Pkg, ext.roots)
	if !isRoot {
		ext.logf("skipping packages resolution for %v (not a root: %v)", from, ext.roots)
		return
	}

	var packages []string

	matches := ix.FindRulesByImportWithConfig(c, resolve.ImportSpec{
		Lang: languageName,
		Imp:  starlarkPackageKind,
	}, languageName)
	for _, m := range matches {
		depLabel := m.Label.Rel(from.Repo, from.Pkg)
		if strings.HasPrefix(depLabel.Pkg, root) {
			packages = append(packages, depLabel.String())
		}
	}

	if len(packages) > 0 {
		sort.Strings(packages)
		r.SetAttr("packages", packages)
	}
}

func (ext *starlarkRepositoryLang) starlarkModuleLibraryResolve(c *config.Config, ix *resolve.RuleIndex, _ *repo.RemoteCache, r *rule.Rule, _ interface{}, from label.Label) {
	// only perform resolve if this is one of the roots
	root, isRoot := getMatchingRoot(from.Pkg, ext.roots)
	if !isRoot {
		ext.logf("skipping modules resolution for %v (not a root: %v)", from, ext.roots)
		return
	}

	var modules []string

	// fetch all starlark_module rules, then filter by the ones below our root
	matches := ix.FindRulesByImportWithConfig(c, resolve.ImportSpec{
		Lang: languageName,
		Imp:  starlarkModuleKind,
	}, languageName)
	for _, m := range matches {
		depLabel := m.Label.Rel(from.Repo, from.Pkg)
		if strings.HasPrefix(depLabel.Pkg, root) {
			modules = append(modules, depLabel.String())
		}
	}

	if len(modules) > 0 {
		sort.Strings(modules)
		r.SetAttr("modules", modules)
	}
}

// Before implements part of the language.LifecycleManager interface.
func (ext *starlarkRepositoryLang) Before(context.Context) {
	ext.logf("Lifecycle: Before() called")
	ext.logf("roots: %v", ext.roots)
}

// DoneGeneratingRules implements part of the language.FinishableLanguage interface.
func (ext *starlarkRepositoryLang) DoneGeneratingRules() {
	ext.logf("Lifecycle: DoneGeneratingRules() called")
}

// AfterResolvingDeps implements part of the language.LifecycleManager interface.
// This is where we flush and close the log file.
func (ext *starlarkRepositoryLang) AfterResolvingDeps(context.Context) {
	ext.logf("Lifecycle: AfterResolvingDeps() called - flushing and closing log file")
	if ext.logWriter != nil {
		// Sync flushes any buffered data to disk
		_ = ext.logWriter.Sync()
		// Close the file
		_ = ext.logWriter.Close()
		ext.logWriter = nil
	}
}

// logf logs a message using the extension's logger if configured
func (ext *starlarkRepositoryLang) logf(format string, args ...any) {
	if ext.logger != nil {
		ext.logger.Printf(format, args...)
	}
}

func getMatchingRoot(rel string, roots []string) (string, bool) {
	for _, root := range roots {
		if root == rel {
			return root, true
		}
	}
	return "", false
}

type suffixes []string

func (s suffixes) Matches(test string) bool {
	for _, v := range s {
		if strings.HasSuffix(test, v) {
			return true
		}
	}
	return false
}

// LogFunc is a function type for logging messages
type LogFunc func(format string, args ...any)

// deleteFile removes a file and logs any errors
func deleteFile(filename string, logf LogFunc) {
	if err := os.Remove(filename); err != nil {
		logf("ERROR: failed to remove %s: %v", filename, err)
	}
}

// readFileLines reads a file and returns a slice of trimmed non-empty lines,
// excluding comments (lines starting with #).
func readFileLines(filePath string, logf LogFunc) ([]string, error) {
	logf("Reading lines from file: %s", filePath)

	// Open the file
	file, err := os.Open(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			logf("  File does not exist")
			return nil, err
		}
		return nil, fmt.Errorf("failed to open file: %w", err)
	}
	defer file.Close()

	// Scan lines using bufio.Scanner
	scanner := bufio.NewScanner(file)
	var lines []string

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Skip empty lines
		if trimmed == "" {
			continue
		}

		// Skip comments
		if strings.HasPrefix(trimmed, "#") {
			continue
		}

		lines = append(lines, trimmed)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to scan file: %w", err)
	}

	logf("  Read %d non-empty lines", len(lines))
	return lines, nil
}

func isBzlSourceFile(f string) bool {
	return strings.HasSuffix(f, bzlFileType) && !ignoreSuffix.Matches(f)
}

func isBuildPackageFile(f string) bool {
	return f == "BUILD.package" || f == "BUILD.bazel.package"
}

func getBzlFileLoadsStmts(path, rel string, logf LogFunc) (*build.File, []*build.LoadStmt, error) {
	f, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("os.ReadFile(%q) error: %v", path, err)
	}
	ast, err := build.ParseBzl(path, f)
	if err != nil {
		return nil, nil, fmt.Errorf("build.Parse(%q) error: %v", f, err)
	}

	var loads []*build.LoadStmt
	build.WalkOnce(ast, func(expr *build.Expr) {
		n := *expr
		if l, ok := n.(*build.LoadStmt); ok {
			if lbl, err := label.Parse(l.Module.Value); err == nil {
				l.Module.Value = lbl.Abs("", rel).String()
			} else {
				logf("rel=%q: load parse error: %s %v", rel, l.Module.Value, err)
			}
			loads = append(loads, l)
		}
	})

	return ast, loads, nil
}

// stringListDict creates a Dict expression with string keys and List values
// containing StringExpr elements. Used for representing load statements by file.
func stringListDict(data map[string][]string) *build.DictExpr {
	if len(data) == 0 {
		return &build.DictExpr{}
	}

	// Sort keys for deterministic output
	keys := slices.Sorted(maps.Keys(data))

	var keyValues []*build.KeyValueExpr
	for _, key := range keys {
		values := data[key]

		// Create list of string expressions for the values
		var listExprs []build.Expr
		for _, value := range values {
			listExprs = append(listExprs, &build.StringExpr{Value: value})
		}

		keyValues = append(keyValues, &build.KeyValueExpr{
			Key:   &build.StringExpr{Value: key},
			Value: &build.ListExpr{List: listExprs},
		})
	}

	return &build.DictExpr{
		List: keyValues,
	}
}
