load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "build_stack_rules_proto",
    path = "../../../../../",
)

load("@build_stack_rules_proto//github.com/stackb/grpc.js:deps.bzl", "grpcjs_deps")

grpcjs_deps()

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()
