load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "proto_go_modules",
    srcs = [
        "language.go",
        "rule.go",
    ],
    importpath = "github.com/stackb/rules_proto/language/proto_go_modules",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//language",
        "@bazel_gazelle//repo",
        "@bazel_gazelle//resolve",
        "@bazel_gazelle//rule",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = ["BUILD.bazel"] + glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
