package proto_go_modules

import (
	"flag"
	"log"
	"strconv"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const (
	protoGoModulesLanguageName = "proto_go_modules"
	enableDirective            = "proto_go_modules_enable"
)

type Config interface {
	LoadName() string
	IndexKinds() map[string]bool
}

func NewLanguage() language.Language {
	l := &ProtoGoModulesLanguage{}
	return l
}

// ProtoGoModulesLanguage implements language.Language.
type ProtoGoModulesLanguage struct {
	enabled    bool
	loadName   string
	indexKinds string
	modules    *protoGoModules
}

func (l ProtoGoModulesLanguage) LoadName() string {
	return l.loadName
}

func (l ProtoGoModulesLanguage) IndexKinds() map[string]bool {
	kinds := make(map[string]bool)
	for _, kind := range strings.Split(l.indexKinds, ",") {
		kinds[kind] = true
	}
	return kinds
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (l *ProtoGoModulesLanguage) Name() string { return protoGoModulesLanguageName }

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (l *ProtoGoModulesLanguage) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&l.loadName, "proto_go_modules_load_name", "@build_stack_rules_proto//rules/go:proto_go_modules.bzl", "Load source for the go_module and go_modules rule symbols")
	fs.StringVar(&l.indexKinds, "proto_go_modules_index_kinds", "proto_go_library", "Rule kinds to index as proto_go_modules deps")
}

func (l *ProtoGoModulesLanguage) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	l.modules = newProtoGoModules(l)
	return nil
}

func (*ProtoGoModulesLanguage) KnownDirectives() []string {
	return []string{enableDirective}
}

// Configure implements config.Configurer
func (l *ProtoGoModulesLanguage) Configure(c *config.Config, rel string, f *rule.File) {
	if f == nil {
		return
	}
	for _, d := range f.Directives {
		if d.Key == enableDirective {
			want, err := strconv.ParseBool(d.Value)
			if err != nil {
				log.Panicln("malformed directive:", d, err)
			}
			l.enabled = want
		}
	}
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (l *ProtoGoModulesLanguage) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{
		l.modules.kind(): l.modules.kindInfo(),
	}
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (l *ProtoGoModulesLanguage) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		l.modules.loadInfo(),
	}
}

// ApparentLoads implements the optional interface language.ModuleAwareLanguage
func (l *ProtoGoModulesLanguage) ApparentLoads(moduleToApparentName func(string) string) []rule.LoadInfo {
	return []rule.LoadInfo{
		l.modules.loadInfo(),
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*ProtoGoModulesLanguage) Fix(c *config.Config, f *rule.File) {}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (l *ProtoGoModulesLanguage) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*ProtoGoModulesLanguage) Embeds(r *rule.Rule, from label.Label) []label.Label { return nil }

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (l *ProtoGoModulesLanguage) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw any,
	from label.Label,
) {
	l.modules.resolve(from, r)
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (l *ProtoGoModulesLanguage) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	if !l.enabled {
		return language.GenerateResult{}
	}

	var rules []*rule.Rule
	if r, ok := l.modules.generateRule(args); ok {
		rules = append(rules, r)
	}

	imports := make([]any, len(rules))
	for i, r := range rules {
		imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}
