plugins:
  - name: cpp
    implementation: builtin:cpp
  - name: protoc-gen-grpc-cpp
    implementation: grpc:grpc:cpp
  - name: java
    implementation: builtin:java
  - name: ts_proto
    implementation: stephenh:ts-proto:protoc-gen-ts-proto
    options:
      - "emitImportedFiles=false"
      - "esModuleInterop=true"
  - name: protoc-gen-go
    implementation: golang:protobuf:protoc-gen-go
    deps:
      - "@org_golang_google_protobuf//reflect/protoreflect"
      - "@org_golang_google_protobuf//runtime/protoimpl"
  - name: protoc-gen-go-grpc
    implementation: grpc:grpc-go:protoc-gen-go-grpc
    deps:
      - "@org_golang_google_grpc//:go_default_library"
      - "@org_golang_google_grpc//codes"
      - "@org_golang_google_grpc//status"
rules:
  - name: proto_descriptor_set
    implementation: stackb:rules_proto:proto_descriptor_set
    visibility:
      - //visibility:public
  - name: proto_compile
    implementation: stackb:rules_proto:proto_compile
    visibility:
      - //visibility:public
  - name: proto_cc_library
    implementation: stackb:rules_proto:proto_cc_library
    visibility:
      - //visibility:public
    deps:
      - "@com_google_protobuf//:protobuf"
  - name: grpc_cc_library
    implementation: stackb:rules_proto:grpc_cc_library
    visibility:
      - //visibility:public
    deps:
      - "@com_github_grpc_grpc//:grpc++"
      - "@com_github_grpc_grpc//:grpc++_reflection"
  - name: proto_go_library
    implementation: stackb:rules_proto:proto_go_library
    visibility:
      - //visibility:public
    resolves:
      - "google/protobuf/([a-z]+).proto @org_golang_google_protobuf//types/known/${1}pb"
      - "google/protobuf/(descriptor|plugin).proto @org_golang_google_protobuf//types/${1}pb"
  - name: proto_ts_library
    implementation: stackb:rules_proto:proto_ts_library
    visibility:
      - //visibility:public
    deps:
      - "@//:node_modules/@nestjs/microservices"
      - "@//:node_modules/@types/node"
      - "@//:node_modules/long"
      - "@//:node_modules/protobufjs"
      - "@//:node_modules/rxjs"
languages:
  - name: cpp
    plugins:
      - cpp
      - protoc-gen-grpc-cpp
    rules:
      - proto_compile
      - proto_cc_library
      - grpc_cc_library
  - name: java
    plugins:
      - java
    rules:
      - proto_compile
  - name: go
    plugins:
      - protoc-gen-go
      - protoc-gen-go-grpc
    rules:
      - proto_compile
      - proto_go_library
    enabled: true
  - name: descriptor
    plugins:
      - protoc-gen-go
    rules:
      - proto_descriptor_set
    enabled: false
  - name: ts_proto
    plugins:
      - ts_proto
    rules:
      - proto_compile
      - proto_ts_library

