load("io_bazel_rules_dotnet//dotnet:defs.bzl", "nuget_package")
def packages():
    
    ### Generated by the tool
    nuget_package(
       name = "google.protobuf",
       package = "google.protobuf",
       version = "3.6.1",
       sha256 = "bfa7666aa55e60aa2ee65502966336f812702acaaf7c62d12f276a01ab3aa9a4",
       core_lib = "lib/netstandard1.0/Google.Protobuf.dll",
       net_lib = "lib/net45/Google.Protobuf.dll",
       mono_lib = "lib/net45/Google.Protobuf.dll",
       core_deps = [
           "@io_bazel_rules_dotnet//dotnet/stdlib.core:netstandard.library.dll",
       ],
       net_deps = [
       ],
       mono_deps = [
       ],
       core_files = [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.xml",
       ],
       net_files = [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.xml",
       ],
       mono_files = [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.xml",
       ],
    )
    ### End of generated by the tool
