package gomodules

import (
	"flag"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

func NewLanguage() language.Language {
	return NewGoModulesLanguage("gomodules")
}

// NewGoModulesLanguage create a new GoModulesLanguage Gazelle extension
// implementation.
func NewGoModulesLanguage(name string) *GoModulesLanguage {
	return &GoModulesLanguage{
		name: name,
	}
}

// GoModulesLanguage implements language.Language.
type GoModulesLanguage struct {
	name      string
	enabled   bool
	loadName  string
	targetPkg string
	goModule  *goModule
	goModules *goModules
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (l *GoModulesLanguage) Name() string { return l.name }

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (l *GoModulesLanguage) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.BoolVar(&l.enabled, "gomodules-enabled", false, "Whether the gomodules language is enabled")
	fs.StringVar(&l.loadName, "gomodules-load-name", "@build_stack_rules_proto//rules/go:module.bzl", "Load source for the go_module and go_modules rule symbols")
	fs.StringVar(&l.targetPkg, "gomodules-target-package", "", "Package name where go_modules aggregate rule should be generated")
}

func (l *GoModulesLanguage) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	l.goModule = newGoModule(l.loadName, l.targetPkg)
	l.goModules = newGoModules(l.loadName, l.targetPkg)
	return nil
}

func (*GoModulesLanguage) KnownDirectives() []string {
	return nil
}

// Configure implements config.Configurer
func (l *GoModulesLanguage) Configure(c *config.Config, rel string, f *rule.File) {
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (l *GoModulesLanguage) Kinds() map[string]rule.KindInfo {
	if !l.enabled {
		return nil
	}

	kinds := map[string]rule.KindInfo{
		l.goModule.kind():  l.goModule.kindInfo(),
		l.goModules.kind(): l.goModules.kindInfo(),
	}
	return kinds

}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (l *GoModulesLanguage) Loads() []rule.LoadInfo {
	if !l.enabled {
		return nil
	}

	return []rule.LoadInfo{
		l.goModule.loadInfo(),
		l.goModules.loadInfo(),
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*GoModulesLanguage) Fix(c *config.Config, f *rule.File) {}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (l *GoModulesLanguage) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*GoModulesLanguage) Embeds(r *rule.Rule, from label.Label) []label.Label { return nil }

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (l *GoModulesLanguage) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw interface{},
	from label.Label,
) {
	l.goModules.resolve(from, r, l.goModule.index)
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (l *GoModulesLanguage) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	if !l.enabled {
		return language.GenerateResult{}
	}

	var rules []*rule.Rule

	if r, ok := l.goModule.generate(args.Rel, args); ok {
		rules = append(rules, r)
	}
	if r, ok := l.goModules.generate(args.Rel); ok {
		rules = append(rules, r)
	}

	imports := make([]any, len(rules))
	for i, r := range rules {
		imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}
