local_repository(
    name = "build_stack_rules_proto",
    path = "../../../",
)

load("@build_stack_rules_proto//objc:deps.bzl", "objc_deps")

objc_deps()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
