package protoc

// ProtoPlugin implementations are capable of predicting the sources that are
// generated by a particular protoc plugin.
type ProtoPlugin interface {
	// // Label returns the unique name for the plugin
	// Label() label.Label

	// ShouldApply asks the plugin: for the given proto_library rule, should you
	// be added to the list of plugins to use?  We cannot rely on GeneratedSrcs
	// alone for this information as not all plugins actually generate source
	// code (some only perform validation/checking).
	ShouldApply(rel string, cfg *protoPackageConfig, lib ProtoLibrary) bool

	// GeneratedSrcs inspects the given proto_library and determines what source
	// files will be generated.
	GeneratedSrcs(rel string, cfg *protoPackageConfig, lib ProtoLibrary) []string
}
