load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rules_rust",
    srcs = [
        "proto_rust_library.go",
        "rust_library.go",
    ],
    importpath = "github.com/stackb/rules_proto/v4/pkg/rule/rules_rust",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/protoc",
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//resolve",
        "@bazel_gazelle//rule",
    ],
)

go_test(
    name = "rules_rust_test",
    srcs = ["proto_rust_library_test.go"],
    embed = [":rules_rust"],
    deps = [
        "//pkg/protoc",
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//language/proto",
        "@bazel_gazelle//rule",
        "@com_github_google_go_cmp//cmp",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
    ] + glob(["*.go"]),
    visibility = ["//pkg:__pkg__"],
)
