load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "protobuf",
    srcs = [
        "config.go",
        "fix.go",
        "generate.go",
        "kinds.go",
        "lang.go",
        "lifecycle.go",
        "override.go",
        "resolve.go",
    ],
    importpath = "github.com/stackb/rules_proto/v4/pkg/language/protobuf",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/protoc",
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//language",
        "@bazel_gazelle//repo",
        "@bazel_gazelle//resolve",
        "@bazel_gazelle//rule",
    ],
)

go_test(
    name = "protobuf_test",
    srcs = [
        "config_filemode_test.go",
        "generate_test.go",
        "lifecycle_test.go",
        "override_test.go",
    ],
    embed = [":protobuf"],
    deps = [
        "//pkg/protoc",
        "@bazel_gazelle//config",
        "@bazel_gazelle//label",
        "@bazel_gazelle//language",
        "@bazel_gazelle//language/proto",
        "@bazel_gazelle//resolve",
        "@bazel_gazelle//rule",
        "@bazel_gazelle//testtools",
        "@com_github_google_go_cmp//cmp",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
    ] + glob(["*.go"]),
    visibility = ["//pkg:__pkg__"],
)
