package protobuf

import (
	"log"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"

	"github.com/stackb/rules_proto/pkg/protoc"
)

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (pl *protobufLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	if resolver, ok := r.PrivateAttr(protoc.RuleProviderKey).(protoc.RuleProvider); ok {
		return resolver.Imports(c, r, f)
	}
	return nil
	// // if provides, ok := rule.PrivateAttr(ResolveProvidesKey).([]string); ok {
	// // }

	// srcs := r.AttrStrings("srcs")
	// imports := make([]resolve.ImportSpec, len(srcs))

	// for i, src := range srcs {
	// 	imports[i] = resolve.ImportSpec{
	// 		// Lang is the language in which the import string appears (this
	// 		// should match Resolver.Name).
	// 		Lang: pl.Name(),
	// 		// Imp is an import string for the library.
	// 		Imp: fmt.Sprintf("//%s:%s", f.Pkg, src),
	// 	}
	// 	// protoc.GlobalResolver().Provide(r.Kind(), "srcs", path.Join(f.Pkg, src), resolveLabel)
	// }

	// return imports
}

// OK, ok. think.  What we want is to be able to populate a deps for any language.  Is it possible?
// 1. given an import statement like google/protobuf/any.proto:
// A. try override with:
//
// if l, ok := resolve.FindRuleWithOverride(c, resolve.ImportSpec{Lang: "go", Imp: imp}, "go"); ok {
// 	return l, nil
// }
//
// Then, if nothing there, use:
//
// if l, err := resolveWithIndexGo(c, ix, imp, from); err == nil || err == skipImportError {
// 	return l, err
// } else if err != notFoundError {
// 	return label.NoLabel, err
// }
//
// which is:
//
// matches := ix.FindRulesByImportWithConfig(c, resolve.ImportSpec{Lang: "go", Imp: imp}, "go")
// var bestMatch resolve.FindResult
// var bestMatchIsVendored bool
// var bestMatchVendorRoot string
// var matchError error

// for _, m := range matches {

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*protobufLang) Embeds(r *rule.Rule, from label.Label) []label.Label { return nil }

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (pl *protobufLang) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw interface{},
	from label.Label,
) {
	if r.Kind() == overrideKindName {
		resolveOverrideRule(from.Pkg, r)
		return
	}

	if resolver, ok := r.PrivateAttr(protoc.RuleProviderKey).(protoc.RuleProvider); ok {
		if imports, ok := importsRaw.([]string); ok {
			resolver.Resolve(c, ix, r, imports, from)
		} else {
			log.Panicf("warning: resolve imports: expected []string, got %T", importsRaw)
		}
	}
}

func (*protobufLang) CrossResolve(c *config.Config, ix *resolve.RuleIndex, imp resolve.ImportSpec, lang string) []resolve.FindResult {
	return protoc.GlobalResolver().CrossResolve(c, ix, imp, lang)
}
