load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "build_stack_rules_proto",
    path = "../../../",
)

load("@build_stack_rules_proto//node:deps.bzl", "node_proto_compile")

node_proto_compile()
