// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: example/assets/api_request.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []string               `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiRequest) Reset() {
	*x = ApiRequest{}
	mi := &file_example_assets_api_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiRequest) ProtoMessage() {}

func (x *ApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_assets_api_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiRequest.ProtoReflect.Descriptor instead.
func (*ApiRequest) Descriptor() ([]byte, []int) {
	return file_example_assets_api_request_proto_rawDescGZIP(), []int{0}
}

func (x *ApiRequest) GetHeader() []string {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_example_assets_api_request_proto protoreflect.FileDescriptor

const file_example_assets_api_request_proto_rawDesc = "" +
	"\n" +
	" example/assets/api_request.proto\x12\x0eexample.assets\"$\n" +
	"\n" +
	"ApiRequest\x12\x16\n" +
	"\x06header\x18\x01 \x03(\tR\x06headerB5Z3github.com/stackb/rules_proto/example/assets;assetsb\x06proto3"

var (
	file_example_assets_api_request_proto_rawDescOnce sync.Once
	file_example_assets_api_request_proto_rawDescData []byte
)

func file_example_assets_api_request_proto_rawDescGZIP() []byte {
	file_example_assets_api_request_proto_rawDescOnce.Do(func() {
		file_example_assets_api_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_assets_api_request_proto_rawDesc), len(file_example_assets_api_request_proto_rawDesc)))
	})
	return file_example_assets_api_request_proto_rawDescData
}

var file_example_assets_api_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_assets_api_request_proto_goTypes = []any{
	(*ApiRequest)(nil), // 0: example.assets.ApiRequest
}
var file_example_assets_api_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_assets_api_request_proto_init() }
func file_example_assets_api_request_proto_init() {
	if File_example_assets_api_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_assets_api_request_proto_rawDesc), len(file_example_assets_api_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_assets_api_request_proto_goTypes,
		DependencyIndexes: file_example_assets_api_request_proto_depIdxs,
		MessageInfos:      file_example_assets_api_request_proto_msgTypes,
	}.Build()
	File_example_assets_api_request_proto = out.File
	file_example_assets_api_request_proto_goTypes = nil
	file_example_assets_api_request_proto_depIdxs = nil
}
