// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: example/assets/api_response.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_example_assets_api_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_assets_api_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_example_assets_api_response_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_example_assets_api_response_proto protoreflect.FileDescriptor

const file_example_assets_api_response_proto_rawDesc = "" +
	"\n" +
	"!example/assets/api_response.proto\x12\x0eexample.assets\"9\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB5Z3github.com/stackb/rules_proto/example/assets;assetsb\x06proto3"

var (
	file_example_assets_api_response_proto_rawDescOnce sync.Once
	file_example_assets_api_response_proto_rawDescData []byte
)

func file_example_assets_api_response_proto_rawDescGZIP() []byte {
	file_example_assets_api_response_proto_rawDescOnce.Do(func() {
		file_example_assets_api_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_assets_api_response_proto_rawDesc), len(file_example_assets_api_response_proto_rawDesc)))
	})
	return file_example_assets_api_response_proto_rawDescData
}

var file_example_assets_api_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_assets_api_response_proto_goTypes = []any{
	(*ApiResponse)(nil), // 0: example.assets.ApiResponse
}
var file_example_assets_api_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_assets_api_response_proto_init() }
func file_example_assets_api_response_proto_init() {
	if File_example_assets_api_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_assets_api_response_proto_rawDesc), len(file_example_assets_api_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_assets_api_response_proto_goTypes,
		DependencyIndexes: file_example_assets_api_response_proto_depIdxs,
		MessageInfos:      file_example_assets_api_response_proto_msgTypes,
	}.Build()
	File_example_assets_api_response_proto = out.File
	file_example_assets_api_response_proto_goTypes = nil
	file_example_assets_api_response_proto_depIdxs = nil
}
