load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "prost_serde",
    srcs = ["protoc-gen-prost-serde.go"],
    importpath = "github.com/stackb/rules_proto/v4/pkg/plugin/neoeinstein/prost_serde",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/plugin/neoeinstein/prost",
        "//pkg/protoc",
        "@bazel_gazelle//label",
        "@bazel_gazelle//rule",
    ],
)

go_test(
    name = "prost_serde_test",
    srcs = ["protoc-gen-prost-serde_test.go"],
    deps = [
        ":prost_serde",
        "//pkg/plugintest",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
    ] + glob(["*.go"]),
    visibility = ["//pkg:__pkg__"],
)
