load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "build_stack_rules_proto",
    path = "../../../",
)

load("@build_stack_rules_proto//python:deps.bzl", "python_grpc_library")

python_grpc_library()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_apt_itude_rules_pip//rules:dependencies.bzl", "pip_rules_dependencies")

pip_rules_dependencies()

load("@com_apt_itude_rules_pip//rules:repository.bzl", "pip_repository")

pip_repository(
    name = "grpc_py2_deps",
    python_interpreter = "python2",
    requirements = "@build_stack_rules_proto//python/requirements:grpc.txt",
)

pip_repository(
    name = "grpc_py3_deps",
    python_interpreter = "python3",
    requirements = "@build_stack_rules_proto//python/requirements:grpc.txt",
)
