/* Copyright 2020 The Bazel Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package symbol generates a `starlark_library` target for every `.bzl` file in
// each package.  At the root of the module, a single starlark_bundle is
// populated with deps that include all other starlark_libraries.
//
// The original code for this gazelle extension started from
// https://github.com/bazelbuild/bazel-skylib/blob/main/gazelle/bzl/gazelle.go.
package starlarkbundle

import (
	"flag"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"path/filepath"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const (
	languageName                          = "starlark_bundle"
	starlarkBundleRepoNameDirectiveName   = "starlark_bundle_repo_name"
	starlarkBundleRootDirectiveName       = "starlark_bundle_root"
	starlarkBundleExcludeDirectiveName    = "starlark_bundle_exclude"
	starlarkBundleLogFileDirectiveName    = "starlark_bundle_log_file"
	starlarkModuleDependencyDirectiveName = "module_dependency"
	coarseDependencies                    = true
)

type starlarkBundleLang struct {
	starlarkBundleRoot        *string
	starlarkBundleRepoName    string
	starlarkBundleExcludeDirs []string
	moduleDeps                map[string]string
	starlarkLibraries         map[label.Label]*rule.Rule
	bzlFiles                  map[string]bool
	logFile                   string
	logWriter                 *os.File
	logger                    *log.Logger
}

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &starlarkBundleLang{
		starlarkLibraries: map[label.Label]*rule.Rule{},
		bzlFiles:          map[string]bool{},
		moduleDeps:        map[string]string{},
	}
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (*starlarkBundleLang) Name() string {
	return languageName
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (ext *starlarkBundleLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&ext.logFile, "starlark_bundle_log", "", "path to log file for starlark_bundle extension")
}

func (ext *starlarkBundleLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	if ext.logFile != "" {
		ext.createLogger(ext.logFile)
		ext.logf("CheckFlags: log file initialized from flag: %s", ext.logFile)
	}
	if ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}
	return nil
}

func (*starlarkBundleLang) KnownDirectives() []string {
	return []string{
		starlarkBundleRootDirectiveName,
		starlarkBundleExcludeDirectiveName,
		starlarkBundleLogFileDirectiveName,
		starlarkModuleDependencyDirectiveName,
	}
}

func (ext *starlarkBundleLang) Configure(c *config.Config, rel string, f *rule.File) {
	if f != nil {
		ext.logf("Configure: processing %d directives in %s", len(f.Directives), rel)
		for _, d := range f.Directives {
			switch d.Key {
			case starlarkBundleRootDirectiveName:
				if ext.starlarkBundleRoot != nil {
					log.Fatalf("gazelle:%s should only be set once (refusing to override %q with %q)", starlarkBundleRootDirectiveName, *ext.starlarkBundleRoot, d.Value)
				}
				ext.starlarkBundleRoot = &rel
			case starlarkBundleRepoNameDirectiveName:
				ext.starlarkBundleRepoName = d.Value
			case starlarkBundleExcludeDirectiveName:
				ext.starlarkBundleExcludeDirs = append(ext.starlarkBundleExcludeDirs, d.Value)
			case starlarkModuleDependencyDirectiveName:
				nameVersion := strings.Fields(d.Value)
				if len(nameVersion) != 2 {
					log.Fatalf("malformed directive %s, should be NAME VERSION: %s", starlarkModuleDependencyDirectiveName, d.Value)
				}
				ext.moduleDeps[nameVersion[0]] = nameVersion[1]
				ext.logf("Added module dependency: %q -> %q", nameVersion[0], nameVersion[1])
			case starlarkBundleLogFileDirectiveName:
				ext.createLogger(d.Value)
			}
		}
	}
}

func (ext *starlarkBundleLang) createLogger(logFile string) {
	if logFile != "" {
		f, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0666)
		if err == nil {
			ext.logWriter = f
			ext.logger = log.New(f, "", log.LstdFlags)
		} else {
			log.Fatalf("attempting to open log file: %v", err)
		}
	}
	if false && ext.logger == nil {
		ext.logger = log.New(io.Discard, "", 0)
	}

	ext.logf("Log initialized")
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*starlarkBundleLang) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{}
	maps.Copy(kinds, starlarkLibraryKindInfo)
	maps.Copy(kinds, starlarkBundleKindInfo)
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (*starlarkBundleLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		starlarkLibraryLoadInfo,
		starlarkBundleLoadInfo,
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*starlarkBundleLang) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (ext *starlarkBundleLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	switch r.Kind() {
	case starlarkLibraryKind:
		return starlarkLibraryImports(c, r, f)
	case starlarkBundleKind:
		return starlarkBundleImports(c, r, f)
	}
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*starlarkBundleLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (ext *starlarkBundleLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, importsRaw interface{}, from label.Label) {
	switch r.Kind() {
	case starlarkLibraryKind:
		starlarkLibraryResolve(c, ix, r, importsRaw, from, ext)
	case starlarkBundleKind:
		if coarseDependencies {
			starlarkBundleResolveCoarse(r, ext.starlarkLibraries, ext.moduleDeps)
		} else {
			starlarkBundleResolve(r, ext.starlarkLibraries)

		}
	}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (ext *starlarkBundleLang) GenerateRules(args language.GenerateArgs) (result language.GenerateResult) {
	if ext.starlarkBundleRoot == nil {
		return
	}
	for _, root := range ext.starlarkBundleExcludeDirs {
		if strings.HasPrefix(args.Rel, root) {
			return
		}
	}

	ext.logf("GenerateRules: visiting %s", args.Rel)

	if args.Rel == "" {
		// REPO.bazel causes visibility issues if the root BUILD file has been
		// deleted but still referencing non-existent rules.  This should be
		// moved to the part where gazelle cleans up build files.
		repoFile := filepath.Join(args.Config.RepoRoot, "REPO.bazel")
		if _, err := os.Stat(repoFile); err == nil {
			ext.logf("Removing REPO.bazel from root package")
			if err := os.Remove(repoFile); err != nil {
				ext.logf("ERROR: failed to remove REPO.bazel: %v", err)
			}
		}

		bazelIgnore := filepath.Join(args.Config.RepoRoot, "REPO.bazel")
		if _, err := os.Stat(bazelIgnore); err == nil {
			if err := ext.removeAbsolutePathsFromBazelignore(bazelIgnore); err != nil {
				ext.logf("ERROR: failed to cleanup .bazelignore file: %v", err)
			}
		}
	}

	for _, r := range []language.GenerateResult{
		starlarkLibraryGenerate(args, ext.starlarkLibraries, ext),
		starlarkBundleGenerate(args, ext.starlarkBundleRoot),
	} {
		result.Gen = append(result.Gen, r.Gen...)
		result.Imports = append(result.Imports, r.Imports...)
		result.Empty = append(result.Empty, r.Empty...)
	}

	return
}

func (ext *starlarkBundleLang) getModuleDependencyRepoName(repo string) (string, bool) {
	ext.logf("getModuleDependencyRepoName called with repo=%q", repo)
	if repo == "" {
		ext.logf("  returning early for empty repo: @")
		return "@", true
	}
	if mappedRepo, ok := ext.moduleDeps[repo]; ok {
		ext.logf("  found mapping: %q -> %q", repo, mappedRepo)
		return mappedRepo, true
	} else {
		ext.logf("  unknown module dependency: %q (known deps: %v)", repo, ext.moduleDeps)
		// log.Fatalf("unknown module dependency: %q", repo)
		return repo, false
	}
}

// logf logs a message using the extension's logger if configured
func (ext *starlarkBundleLang) logf(format string, args ...any) {
	if ext.logger != nil {
		ext.logger.Printf(format, args...)
	}
}

// removeAbsolutePathsFromBazelignore reads a .bazelignore file and removes
// any lines that are absolute paths (starting with /).
func (ext *starlarkBundleLang) removeAbsolutePathsFromBazelignore(bazelignorePath string) error {
	ext.logf("Checking .bazelignore file: %s", bazelignorePath)

	// Read the file
	content, err := os.ReadFile(bazelignorePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // File doesn't exist, nothing to do
		}
		return fmt.Errorf("failed to read .bazelignore: %w", err)
	}

	// Split into lines
	lines := strings.Split(string(content), "\n")
	var filteredLines []string
	removedCount := 0

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		// Keep the line if it's not an absolute path
		if trimmed == "" || !strings.HasPrefix(trimmed, "/") {
			filteredLines = append(filteredLines, line)
		} else {
			ext.logf("  Removing absolute path from .bazelignore: %q", trimmed)
			removedCount++
		}
	}

	// If nothing changed, don't rewrite the file
	if removedCount == 0 {
		ext.logf("  No absolute paths found in .bazelignore")
		return nil
	}

	// Write back the filtered content
	newContent := strings.Join(filteredLines, "\n")
	if err := os.WriteFile(bazelignorePath, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("failed to write .bazelignore: %w", err)
	}

	ext.logf("  Removed %d absolute path(s) from .bazelignore", removedCount)
	return nil
}
