local_repository(
    name = "build_stack_rules_proto",
    path = "../build_stack_rules_proto",
)

register_toolchains("@build_stack_rules_proto//toolchain")

load("@build_stack_rules_proto//deps:core_deps.bzl", "core_deps")

load("@build_stack_rules_proto//deps:protobuf_deps.bzl", "protobuf_deps")

core_deps()

protobuf_deps()
