load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#
# Declare dependency on build_stack_rules_proto
#
local_repository(
    name = "build_stack_rules_proto",
    path = "../..",
)

#
# Establish the @rules_proto external workspace 
#
load("@build_stack_rules_proto//third_party/rules_proto:repository.bzl", "rules_proto")

rules_proto()

#
# Execute @rules_proto dependencies - this brings in
# com_google_protobuf//:protoc 
#
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()


#
# Establish the @io_grpc_grpc_java external workspace 
#
load("@build_stack_rules_proto//third_party/io_grpc_grpc_java:repository.bzl", "io_grpc_grpc_java")

io_grpc_grpc_java()

#
# Execute @io_grpc_grpc_java dependencies
#
load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories()
