load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "build_stack_rules_proto",
    path = "../../../",
)

load("@build_stack_rules_proto//rust:deps.bzl", "rust_grpc_compile")

rust_grpc_compile()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@build_stack_rules_proto//rust/cargo:crates.bzl", "raze_fetch_remote_crates")

raze_fetch_remote_crates()
