http_archive(
  name = "com_github_stackb_distoless_bazel",
  urls = [
    "https://github.com/stackb/distroless-bazel/archive/16890ad6bc0adf4613bdb63bf35fedba5bbd6070.tar.gz",
  ],
  strip_prefix = "distroless-bazel-16890ad6bc0adf4613bdb63bf35fedba5bbd6070",
  sha256 = "a5b5ef793a3dcaa2de1d265826e06d40839f2ebc87bbc0e288e158b4b8671e54",
)


load("@com_github_stackb_distoless_bazel//:deps.bzl", "distroless_bazel_repositories", "bazel_dependencies")
distroless_bazel_repositories()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

load("@com_github_stackb_distoless_bazel//:container.bzl", "container_dependencies")
container_dependencies()

bazel_dependencies()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    container_repositories = "repositories",
    "container_pull",
)

container_pull(
    name = "bazel",
    registry = "l.gcr.io",
    repository = "google/bazel",
    tag = "0.19.2",
)

load(
    "@distroless//package_manager:package_manager.bzl",
    "package_manager_repositories",
    "dpkg_src",
    "dpkg_list",
)

package_manager_repositories()

dpkg_src(
    name = "debian_stretch",
    arch = "amd64",
    distro = "stretch",
    sha256 = "4cb2fac3e32292613b92d3162e99eb8a1ed7ce47d1b142852b0de3092b25910c",
    snapshot = "20180406T095535Z",
    url = "http://snapshot.debian.org/archive",
)

dpkg_src(
    name = "debian_stretch_backports",
    arch = "amd64",
    distro = "stretch-backports",
    sha256 = "2863af9484d2d6b478ef225a8c740dac9a14015a594241a0872024c873123cdd",
    snapshot = "20180406T095535Z",
    url = "http://snapshot.debian.org/archive",
)

dpkg_src(
    name = "debian_stretch_security",
    package_prefix = "http://snapshot.debian.org/archive/debian-security/20180405T165926Z/",
    packages_gz_url = "http://snapshot.debian.org/archive/debian-security/20180405T165926Z/dists/stretch/updates/main/binary-amd64/Packages.gz",
    sha256 = "a503fb4459eb9e862d080c7cf8135d7d395852e51cc7bfddf6c3d6cc4e11ee5f",
)

dpkg_list(
    name = "package_bundle",
    packages = [
        "xz-utils",
        "liblzma5",
        "bzip2",
        "libbz2-1.0",
        # "ruby",
        # "ruby2.3",
        # "libruby2.3",
        # "libgmp10",
    ],
    sources = [
        "@debian_stretch_security//file:Packages.json",
        "@debian_stretch_backports//file:Packages.json",
        "@debian_stretch//file:Packages.json",
    ],
)

