load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#
# Declare dependency on build_stack_rules_proto
#
local_repository(
    name = "build_stack_rules_proto",
    path = "../..",
)

#
# Establish the @rules_proto external workspace 
#
load("@build_stack_rules_proto//third_party/rules_proto:repository.bzl", "rules_proto")

rules_proto()

#
# Execute @rules_proto dependencies - this brings in
# com_google_protobuf//:protoc 
#
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()


#
# Establish the @io_bazel_rules_closure external workspace 
#
load("@build_stack_rules_proto//third_party/io_bazel_rules_closure:repository.bzl", "io_bazel_rules_closure")

io_bazel_rules_closure()

#
# Execute @io_bazel_rules_closure dependencies
#
load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")

rules_closure_dependencies()

rules_closure_toolchains()

#
# Establish the @rules_proto_grpc external workspace 
#
load("@build_stack_rules_proto//third_party/rules_proto_grpc:repository.bzl", "rules_proto_grpc")

rules_proto_grpc()

#
# Register the rules_proto_grpc toolchain
#
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()
